### ISSUE TITLE
YAML?

### ISSUE THREAD

**Issue by dret** [jsonii/awesome-json-next#3]
not sure how exactly the candidates get selected. but it seems with YAML being pretty popular and building on top of JSON, it would be a good candidate to add to the list?

**Comment by geraldb** [comment]
@dret  Good point. I am a fan of YAML too - see the Awesome YAML page -> https://github.com/datatxt/awseome-yaml   However, with significant whitespaces, and more it's not really any more a JSON next candidate, in my humble opinon. YAML is YAML ;-) Like XML, TOML (INI), etc. it's it own format family. Cheers.
