### ISSUE TITLE
Mark?

### ISSUE THREAD

**Issue by henry-luo** [jsonii/awesome-json-next#4]
Time to add [Mark ](https://mark.js.org) to the list? :-)

**Comment by henry-luo** [comment]
Thanks for compiling such a list. I did not notice that there are so many JSON next around.

Glad to join the family! :-)

**Comment by geraldb** [comment]
@henry-luo  Good luck with {mark}. Added to list, see <https://github.com/json-next/awesome-json-next#objective-markup-notation---mark> All the best. Cheers.

**Comment by henry-luo** [comment]
Thanks!
